// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveFile(arg1:string,arg2:string,arg3:number,arg4:string,arg5:Array<number>,arg6:string):Promise<string>;

export function SelectDirectory():Promise<string>;
